# Generated by Django 3.0.7 on 2020-06-29 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tecnigo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tecnicalsupportstaff',
            old_name='name',
            new_name='FIRST_NAME',
        ),
        migrations.AddField(
            model_name='tecnicalsupportstaff',
            name='LAST_NAME',
            field=models.CharField(default='none', max_length=40),
            preserve_default=False,
        ),
    ]
