# Generated by Django 3.0.7 on 2020-06-29 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tecnigo', '0002_auto_20200629_1558'),
    ]

    operations = [
        migrations.AddField(
            model_name='tecnicalsupportstaff',
            name='ADDRESS',
            field=models.CharField(default='null', max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tecnicalsupportstaff',
            name='AGE',
            field=models.IntegerField(default=0, max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tecnicalsupportstaff',
            name='CELL_PHONE',
            field=models.IntegerField(default=0, max_length=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tecnicalsupportstaff',
            name='EDUCATION',
            field=models.CharField(default='null', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tecnicalsupportstaff',
            name='ID',
            field=models.IntegerField(default=0, max_length=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tecnicalsupportstaff',
            name='PHONE',
            field=models.IntegerField(default=0, max_length=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tecnicalsupportstaff',
            name='PHONE_OS',
            field=models.CharField(default='null', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tecnicalsupportstaff',
            name='PROFESSION',
            field=models.CharField(default='null', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tecnicalsupportstaff',
            name='Q1_ANSWER',
            field=models.CharField(default='null', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tecnicalsupportstaff',
            name='STORY',
            field=models.CharField(default='null', max_length=500),
            preserve_default=False,
        ),
    ]
