# Generated by Django 3.0.7 on 2020-06-29 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tecnigo', '0003_auto_20200629_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tecnicalsupportstaff',
            name='AGE',
            field=models.IntegerField(default=0, max_length=3),
        ),
        migrations.AlterField(
            model_name='tecnicalsupportstaff',
            name='CELL_PHONE',
            field=models.IntegerField(default=0, max_length=12),
        ),
        migrations.AlterField(
            model_name='tecnicalsupportstaff',
            name='ID',
            field=models.IntegerField(default=0, max_length=8),
        ),
        migrations.AlterField(
            model_name='tecnicalsupportstaff',
            name='PHONE',
            field=models.IntegerField(default=0, max_length=12),
        ),
    ]
