# Generated by Django 3.0.7 on 2020-07-24 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tecnigo', '0006_auto_20200707_2227'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tecnicalsupportstaff',
            old_name='HomeLocationLatitude',
            new_name='HOME_LOCATION_LATITUDE',
        ),
        migrations.RenameField(
            model_name='tecnicalsupportstaff',
            old_name='HomeLocationLongitude',
            new_name='HOME_LOCATION_LONGITUDE',
        ),
    ]
